### ISSUE TITLE
The window that displays the code could be toggable

### ISSUE THREAD

**Issue by serudda** [Stylepill/Stylepill#13]
Mobile Safari 11.0
iOS 11.2.1
Phone (375 x 559)

![screen shot 2017-12-19 at 12 24 09 pm](https://user-images.githubusercontent.com/10075532/34170075-8c41c564-e4b7-11e7-9450-1e68bf840fbd.png)

**Comment by pedrorio** [comment]
Also on chrome version 63.0

**Comment by serudda** [comment]
@pedrorio Thanks for your feedback. We're going to work on it for the next release.

**Comment by serudda** [comment]
@pedrorio It's done. It already included in the next release. You can see our weekly progress here: 
https://github.com/Stylepill/Stylepill/projects/1

Thanks a lot for your feedback.

**Comment by serudda** [comment]
It's already included in the last release v0.4.17. Thanks for your feedback.
