### ISSUE TITLE
I want create components too

### ISSUE THREAD

**Issue by stevenselcuk** [Stylepill/Stylepill#14]
Hi everyone, it's me Selçuk. 
First of all Rosita & Sergio you're creating really really good stuff! I really love it. And I can not wait to create some componentz. 

See u.

**Comment by serudda** [comment]
@selcukahmet It's a pleasure to find messages like this. Thank thank thank!!!. It helps us to work hard!.

**Comment by serudda** [comment]
You'll be able to create UI Components and Projects right now :). Included in the last release: v.0.4.17
